export const profile = {
  name: "Ivan Roganov",
  aliases: ["nurked", "N'urk", "IFCLLC", "Ivan's Freacking Company"],
  position: "IT Expert & Educator",
  company: "Investment Fidelity Company LLC",
  location: "Clearwater, Florida",
  expertise: [
    "Legacy System Modernization",
    "IT Troubleshooting",
    "Software Development",
    "Education",
    "Technical Writing",
    "Team Leadership",
    "Project Recovery",
    "Systems Architecture",
  ],
  social: {
    linkedin: "https://www.linkedin.com/in/ivan-roganov/",
    telegram: "https://t.me/nurked",
    medium: "https://medium.com/@ifcllc",
    whatsapp: "+1 (707) 968-7533",
    github: "https://github.com/nurked",
  },
  contact: {
    email: "ivan@roganov.me",
    businessEmail: "ceo@investmentfidelity.company",
    phone: "+1 (707) 968-7533",
  },
  meta: {
    title: "Ivan Roganov - IT Expert, Educator & Problem Solver | IFCLLC",
    description:
      "Veteran IT troubleshooter with 15+ years experience in solving complex technical challenges and modernizing legacy systems. Technical writer, educator and team leader specializing in project recovery and systems architecture.",
    keywords: [
      "Ivan Roganov",
      "IFCLLC",
      "nurked",
      "IT Expert",
      "Software Development",
      "Legacy Systems",
      "Education",
      "Technical Writing",
      "Project Recovery",
      "Systems Architecture",
      "Team Leadership",
      "Technology Consultant",
      "Florida IT Expert",
      "Clearwater Technology Consultant",
    ],
    images: {
      profile: "/ivan.png",
      logo: "/logo.png",
    },
  },
};
