export const profile = {
  name: "Ivan Roganov",
  aliases: ["nurked", "N'urk", "IFCLLC", "Ivan's Freacking Company"],
  position: "AI Integration & Enterprise Systems Engineer",
  company: "Investment Fidelity Company LLC",
  companySite: "https://investmentfidelity.company",
  location: "Clearwater, Florida",
  expertise: [
    "AI Integration & LLM Systems",
    "AI Agents & Workflow Automation",
    "Enterprise AI Strategy",
    "Legacy System Modernization",
    "IT Troubleshooting",
    "Software Development",
    "Education",
    "Technical Writing",
    "Team Leadership",
    "Project Recovery",
    "Systems Architecture",
  ],
  social: {
    linkedin: "https://www.linkedin.com/in/ivan-roganov/",
    telegram: "https://t.me/nurked",
    medium: "https://medium.com/@ifcllc",
    whatsapp: "+1 (707) 968-7533",
    github: "https://github.com/nurked",
  },
  contact: {
    email: "ivan@roganov.me",
    businessEmail: "ceo@investmentfidelity.company",
    phone: "+1 (707) 968-7533",
  },
  meta: {
    title: "Ivan Roganov - AI Integration & Enterprise Systems Engineer | IFCLLC",
    description:
      "Enterprise engineer for the AI era: 15+ years modernizing legacy systems, now integrating LLMs and AI agents into real businesses. Founder of Investment Fidelity Company LLC. Available for AI integration projects.",
    keywords: [
      "Ivan Roganov",
      "IFCLLC",
      "nurked",
      "AI Integration",
      "AI Integration Consultant",
      "Enterprise AI",
      "LLM Integration",
      "AI Agents",
      "AI Workflow Automation",
      "AI Consultant Florida",
      "IT Expert",
      "Software Development",
      "Legacy Systems",
      "Legacy System Modernization",
      "Education",
      "Technical Writing",
      "Project Recovery",
      "Systems Architecture",
      "Team Leadership",
      "Technology Consultant",
      "Florida IT Expert",
      "Clearwater Technology Consultant",
    ],
    images: {
      profile: "/ivan.png",
      logo: "/logo.png",
    },
  },
};
